### ISSUE TITLE
Finish Lab 1

### ISSUE THREAD

**Issue by paleobiologyGrader** [akufner/GitRepositories#2]
You'll need to finish Lab 1 to receive full credit. You can consult with the answer key I put up online.

**Comment by paleobiologyGrader** [comment]
Hey, I know you've been working on this. Do me a favor and let me know when you are ready to submit it.

**Comment by akufner** [comment]
Hey, sorry I've been busy, but I just finished it.

-Aaron

**Comment by paleobiologyGrader** [comment]
No problem. Didn't mean to rush you. I just wanted to make sure that you didn't do all the work and then forget to get credit!
